# Generated by Django 3.1.4 on 2021-02-02 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='pgn',
            field=models.TextField(null=True),
        ),
    ]
